apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: puptoo-config
    files:
      - config.json
